"""empty message

Revision ID: 3fa1060fd6db
Revises: af8b1d1c5061
Create Date: 2018-12-27 16:23:03.953428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa1060fd6db'
down_revision = 'af8b1d1c5061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aisle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('bin', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('bin', sa.Column('aisle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bin', 'aisle', ['aisle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bin', type_='foreignkey')
    op.drop_column('bin', 'aisle_id')
    op.drop_column('bin', 'active')
    op.drop_table('aisle')
    # ### end Alembic commands ###
