"""empty message

Revision ID: af8b1d1c5061
Revises: 566793e66986
Create Date: 2018-12-24 15:24:14.975153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af8b1d1c5061'
down_revision = '566793e66986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lot', 'bin_')
    op.drop_column('lot', 'item')
    op.drop_column('lot', 'qty_')
    op.add_column('pallet', sa.Column('lot_', sa.String(length=60), nullable=True))
    op.add_column('pallet', sa.Column('qty_', sa.Float(), nullable=True))
    op.drop_index('name', table_name='pallet')
    op.drop_constraint('pallet_ibfk_3', 'pallet', type_='foreignkey')
    op.create_foreign_key(None, 'pallet', 'lot', ['lot_'], ['name'])
    op.drop_column('pallet', 'num_of_pieces')
    op.drop_column('pallet', 'lot_id')
    op.drop_column('pallet', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pallet', sa.Column('name', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('pallet', sa.Column('lot_id', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('pallet', sa.Column('num_of_pieces', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pallet', type_='foreignkey')
    op.create_foreign_key('pallet_ibfk_3', 'pallet', 'lot', ['lot_id'], ['name'])
    op.create_index('name', 'pallet', ['name'], unique=True)
    op.drop_column('pallet', 'qty_')
    op.drop_column('pallet', 'lot_')
    op.add_column('lot', sa.Column('qty_', mysql.FLOAT(), nullable=True))
    op.add_column('lot', sa.Column('item', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('lot', sa.Column('bin_', mysql.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
